// Generated/maintained localization catalog for WP-20. Do not place user-facing copy in UI source.
const Map<String, String> appTextTr = {
  'u0001': 'Demo hazırlanıyor',
  'u0002': 'Demo verisi açılamadı',
  'u0003': 'Yerel başlangıç verisi güvenli biçimde yüklenemedi. ',
  'u0004': 'Tekrar dene',
  'u0005': 'Bildirimin alındı',
  'u0006': 'Ne tür bir sorun var?',
  'u0007': 'En uygun türü seç. Fotoğraf analizinden sonra öneriyi değiştirebilirsin.',
  'u0008': 'Fotoğraf ekle',
  'u0009': 'Sorunu yaklaşmadan, güvenli bir noktadan ve mümkünse tek karede göster.',
  'u0010': 'Fotoğraf kalitesi ve formatı kontrol edildi',
  'u0011': 'EXIF ve ek metadata temizlendi',
  'u0012': 'Yüz/plaka için insan gizlilik kontrolü gerekli',
  'u0013': 'Kontrol tamamlanana kadar kamusal kopya oluşturulmaz.',
  'u0014': 'Konumu doğrula',
  'u0015': 'Önerilen konumu kontrol et veya koordinatı elle düzelt.',
  'u0016': 'Kısa bilgi ekle',
  'u0017': 'Ne gördüğünü ve güvenli yaklaşım bilgisini yaz. Kişisel bilgi ekleme.',
  'u0018': 'Kontrol et ve gönder',
  'u0019': 'Mevcut olayı doğrula',
  'u0020': 'Yeni bildirim oluştur',
  'u0021': 'Göndererek, bulanıklaştırılmış/güvenli kamusal önizleme üretilemediğinde fotoğrafın yalnız yetkili personelce görüleceğini kabul edersin.',
  'u0022': 'Sorun bildir',
  'u0023': 'Bildirimlerim',
  'u0024': 'Aktif',
  'u0025': 'Tamamlanan',
  'u0026': 'Tümü',
  'u0027': 'İşlem geçmişi',
  'u0028': 'Gönderdiğin fotoğraf',
  'u0029': 'Orijinal görüntü kamusal yanıtta yer almaz.',
  'u0030': 'Çözüm geri bildirimi',
  'u0031': '“Sorun sürüyor” seçimi otomatik yeniden açmaz; insan inceleme sinyali oluşturur.',
  'u0032': 'Bildirim merkezi',
  'u0033': 'Yalnız okunmamış',
  'u0034': 'KVKK hakları',
  'u0035': 'Erişim, düzeltme, silme ve otomatik değerlendirmeye itiraz talepleri takip numarasıyla kaydedilir ve insan incelemesine gider.',
  'u0036': 'Kullanım kısıtı',
  'u0037': 'İncelemede',
  'u0038': 'İtiraz et',
  'u0039': 'Hesap silme',
  'u0040': 'Hesabımı silme talebi oluştur',
  'u0041': 'Bu işlem yeniden doğrulama ve açık ikinci onay ister.',
  'u0042': 'Başlat',
  'u0043': 'Vazgeç',
  'u0044': 'Gönder',
  'u0045': 'Yeniden doğrulama',
  'u0046': 'Doğrula',
  'u0047': 'Hesap silme talebini onayla',
  'u0048': 'Talep açıldıktan sonra yeni bildirim gönderemezsin. Mevcut kayıtların silme/anonimleştirme kararı KVKK iş akışında insan tarafından ele alınır.',
  'u0049': 'Talebi oluştur',
  'u0050': 'Kısıta itiraz',
  'u0051': 'Yol ve kaldırım',
  'u0052': 'Trafik ve sinyalizasyon',
  'u0053': 'Su ve altyapı',
  'u0054': 'Aydınlatma',
  'u0055': 'Yol Bakım ve Altyapı',
  'u0056': 'Trafik Müdürlüğü',
  'u0057': 'Su Operasyonları',
  'u0058': 'Bu işlem kırmızı public olay üretir. AI tek başına bu eylemi çalıştıramaz.',
  'u0059': 'İnceleme kuyrukları',
  'u0060': 'Bileşen galerisi',
  'u0061': 'Dialog odağı kapalı döngüde tutar ve kapanınca çağıran kontrole döndürür.',
  'u0062': 'Kapat',
  'u0063': 'Mobil ikincil işlem yüzeyi; safe area ve klavye inset’ine uyar.',
  'u0064': 'Bileşenler',
  'u0065': 'Demo sıfırlama için resetDemo yetkisi gerekir.',
  'u0066': 'Paylaşımlı demoda sıfırlama yalnızca sunucu yöneticisine aittir.',
  'u0067': 'Belediye operasyon merkezi',
  'u0068': 'Kuyruk sayıları snapshot domain verisinden anlık türetilir; kritik kayıtlar normal kuyruk altında kaybolmaz.',
  'u0069': 'Öncelikli incelemeler',
  'u0070': 'Şu anda açık inceleme kaydı yok.',
  'u0071': 'Kuyruğa dön',
  'u0072': 'Filtreler',
  'u0073': 'Yol yüzeyi hasarı',
  'u0074': 'Trafik işareti / sinyal',
  'u0075': 'Su altyapısı',
  'u0076': 'Beyoğlu Belediyesi',
  'u0077': 'Üsküdar Belediyesi',
  'u0078': '%25+',
  'u0079': '%50+',
  'u0080': '%75+',
  'u0081': 'Filtreleri temizle',
  'u0082': 'Arama ve filtreler',
  'u0083': 'İnsan kararı',
  'u0084': 'AI yalnız öneri verir; aşağıdaki eylemler yalnız yetkili insan komutuyla yürür.',
  'u0085': 'Yetersiz / doğrulanamayan kanıt',
  'u0086': 'Belediye görev alanı dışında',
  'u0087': 'Özel mülkiyet / özel sorumluluk',
  'u0088': 'Hizmet / yetki sınırı dışında',
  'u0089': 'Geçersiz / kötüye kullanım',
  'u0090': 'Kamusal önizlemeyi insan olarak kontrol ettim',
  'u0091': 'Doğrulama kırmızı public incident oluşturur; orijinal medya public projection’a girmez.',
  'u0092': 'Doğrula + yayınla',
  'u0093': 'Reddet',
  'u0094': 'Kapsam dışı',
  'u0095': 'İBB birimini değiştir',
  'u0096': 'Yanlış yönlendirmeyi geri al',
  'u0097': 'Ek bilgi iste',
  'u0098': 'Hedef seç',
  'u0099': 'Bildirimi birleştir',
  'u0100': 'Demo ilçe belediyesi',
  'u0101': 'İlçe belediyesine yönlendir',
  'u0102': 'Devral',
  'u0103': 'Onayla',
  'u0104': 'AI sonucu yok. Kayıt manuel inceleme olarak ele alınır.',
  'u0105': 'Bağlı kurumsal kaynak kaydı yok.',
  'u0106': 'Kaynak sağlık sinyalleri birbiriyle çelişiyor.',
  'u0107': 'Orijinal içeriği açmak için iş gerekçesi zorunludur; her erişim immutable audit olayına yazılır.',
  'u0108': 'Gerekçeyle aç',
  'u0109': 'Orijinal medya bu rol için gizlidir.',
  'u0110': 'Orijinal medya erişimi',
  'u0111': 'Eriş',
  'u0112': 'Yakın ve aynı kategoriye ait belirgin bir merge adayı yok.',
  'u0113': 'Citizen-visible timeline olayı yok.',
  'u0114': 'Yetkili audit',
  'u0115': 'Henüz bağlı UrbanIncident yok. Doğrulama veya merge ile oluşturulabilir.',
  'u0116': 'Merge karşılaştırması',
  'u0117': 'Veri kaynakları',
  'u0118': 'Kaynak durumu, kaynak zamanı ve sisteme alınma zamanı ayrı gösterilir. Eski veri güncelmiş gibi sunulmaz.',
  'u0119': 'GTFS şema kanıtını çalıştır',
  'u0120': 'Yetkili manuel olay',
  'u0121': '153 sözleşme simülasyonu',
  'u0122': 'JSON/CSV fixture içe aktar',
  'u0123': 'JSON dışa aktar',
  'u0124': 'CSV dışa aktar',
  'u0125': 'Kaynak',
  'u0126': 'API / CSV',
  'u0127': 'Durum',
  'u0128': 'Son başarılı alım',
  'u0129': 'Kaynak zamanı',
  'u0130': 'Sisteme alım',
  'u0131': 'Kabul / Karantina',
  'u0132': 'Son hata',
  'u0133': 'İşlem',
  'u0134': 'Doğrulamalı fixture import',
  'u0135': 'JSON',
  'u0136': 'CSV',
  'u0137': 'Doğrula ve içe aktar',
  'u0138': 'Kaydet',
  'u0139': 'Kullanıcı ve rol yönetimi',
  'u0140': 'Kritik rol/permission değişiklikleri ikinci onay gerektirir ve immutable audit olayına dönüşür.',
  'u0141': 'Rol ve permission düzenle',
  'u0142': 'Kademeli kullanım kısıtı',
  'u0143': 'Kararı kaydet',
  'u0144': 'Devam',
  'u0145': 'İkinci onay',
  'u0146': 'Immutable audit explorer',
  'u0147': 'Audit olayları bu ekrandan değiştirilemez veya silinemez; yalnız filtrelenir ve dışa aktarılır.',
  'u0148': 'CSV kopyala',
  'u0149': 'JSON kopyala',
  'u0150': 'Bu filtreyle audit olayı yok.',
  'u0151': 'KVKK ve güvenlik talepleri',
  'u0152': 'Erişim, düzeltme, silme ve otomatik değerlendirmeye itiraz talepleri insan kararıyla kapanır.',
  'u0153': 'Açık KVKK talebi bulunmuyor.',
  'u0154': 'Kabul et',
  'u0155': 'Gerekçeli reddet',
  'u0156': 'Kullanım kısıtları ve itirazlar',
  'u0157': 'Aktif veya geçmiş restriction kaydı yok.',
  'u0158': 'RBAC permission matrisi',
  'u0159': 'Reviewer · Unit · Planner · System Admin · Demo Supervisor',
  'u0160': 'Birim görevleri ve saha çözümü',
  'u0161': 'SLA bir hedef aralığıdır; vatandaş ekranında garanti dili kullanılmaz.',
  'u0162': 'Çevrimdışı · salt okunur',
  'u0163': 'Bu filtrede görev yok.',
  'u0164': 'Bu filtrede saha görevi bulunmuyor.',
  'u0165': 'SLA hedefi aşıldı',
  'u0166': 'Saha ekibine ata',
  'u0167': 'Saha çalışmasını başlat',
  'u0168': 'Gecikme ve yeni tahmini kaydet',
  'u0169': 'Fotoğraf ekleme',
  'u0170': 'Çözüldü olarak kaydet',
  'u0171': 'Çalışma planlama',
  'u0172': '7. Etki analizini çalıştır',
  'u0173': 'Taslak kaydedilemedi; alanları ve bağlantıyı kontrol edin.',
  'u0174': 'Planlı çalışma bulunamadı.',
  'u0175': 'Açıklanabilir etki analizi',
  'u0176': 'Etki haritası',
  'u0177': 'Zaman çizelgesi',
  'u0178': 'Planlanan başlangıç',
  'u0179': 'Tahmini bitiş',
  'u0180': 'Etkilenen yol ve hatlar',
  'u0181': 'Çakışma gerekçeleri',
  'u0182': 'Kural tabanlı alternatifler',
  'u0183': 'Vatandaş bilgilendirme metni taslağı',
  'u0184': 'Yayın incelemesine gönder',
  'u0185': 'Yayınlama kontrolü',
  'u0186': 'Bu önizleme vatandaş görünümüne yakındır. Sarı pin yalnız insan onayından sonra yayımlanır.',
  'u0187': 'Planlanan çalışma',
  'u0188': 'Kaynak özeti: demo yol/transit bufferları + planlı belediye çalışma zaman aralıkları',
  'u0189': 'Public preview ve zorunlu alanları insan olarak kontrol ettim',
  'u0190': 'Etki analizi tahmin değil; geometri/zaman çakışması ve kullanılan demo referansları açıklanır.',
  'u0191': 'Çalışma sarı planlı pin olarak yayımlandı.',
  'u0192': 'Çalışmayı yayınla',
  'u0193': 'Planlanan',
  'u0194': 'Trafik',
  'u0195': '© OpenStreetMap contributors',
  'u0197': 'Yerel başlangıç verisi güvenli biçimde yüklenemedi. Yeniden deneyebilir veya uygulamayı kapatabilirsiniz.',
  'u0196': 'Bu filtrede gösterilecek kayıt yok.',
  'u0198': 'İlçe, mahalle veya adres ara',
  'u0199': 'Aramayı temizle',
  'u0200': 'Tüm İstanbul’u göster',
  'u0201': 'Bu alanda ara',
  'u0202': 'Erişilebilir liste',
  'u0203': 'Harita görünümü',
  'u0204': 'İstanbul kent olayları haritası. Aynı içerik liste düğmesiyle erişilebilir.',
  'u0205': 'Çevrimdışı harita',
  'u0206': 'Harita döşemeleri alınamadı; kayıtlar yerel altlıkta gösteriliyor.',
  'u0207': 'Örn. Yolun sağ şeridinde derin çökme var.',
  'u0208': 'Enlem',
  'u0209': 'Boylam',
  'u0210': 'Açıklama',
  'u0211': 'İnsan incelemesi güvencesi',
  'u0212': 'AI sonucu yalnız ön analizdir. Yayın ve yönlendirme kararını yetkili personel verir.',
  'u0213': 'Bu adım tamamlanamadı',
  'u0214': 'Gizliliğin korunur',
  'u0215': 'Kamera bilgisi',
  'u0216': 'Konum görünürlüğü',
  'u0217': 'AI ön analizi',
  'u0218': 'Fotoğraftaki metadata temizlenir; yüz veya plaka güvenle işlenemezse görüntü kamusal alana çıkmaz.',
  'u0219': 'Hassas konumlar kamusal görünümde yaklaşık gösterilir; yetkili inceleme kaydı korunur.',
  'u0220': 'Kategori, yönlendirilecek birim ve olası benzer kayıt önerilir. Son karar sende ve yetkili incelemecidedir.',
  'u0221': 'İstenen ek bilgi',
  'u0222': 'İtiraz açıklaması',
  'u0223': 'Çevrimdışı görünüm',
  'u0224': 'Son eşitlenen durum gösteriliyor; yeni taslaklar cihazda korunur.',
  'u0225': 'Bu filtrede bildirim yok',
  'u0226': 'Kaynak güncel olmayabilir',
  'u0227': 'Çözüm kanıtı',
  'u0228': 'İşlem sonucu',
  'u0229': 'Bildirim yok',
  'u0230': 'Bildirim bulunamadı veya bu hesaba ait değil.',
  'u0231': 'Son kaynak eşitlemesi gecikmiş olabilir; işlem geçmişi kanonik kayıttır.',
  'u0232': 'Talep açıklaması',
  'u0233': 'Demo doğrulama kodu',
  'u0234': 'İtiraz gerekçesi',
  'u0235': 'Doğrulanan kategori',
  'u0236': 'Sorumlu birim',
  'u0237': 'Demo kodu: 123456',
  'u0238': 'Canlı güncelleme kesildi',
  'u0239': 'Silme talebi alındı',
  'u0240': 'İncelenecek bildirim yok',
  'u0241': 'Salt okunur mod',
  'u0242': 'Kayıt başka bir istemcide değişti',
  'u0243': 'AI ön analiz mevcut',
  'u0244': 'Harita verisi alınamadı.',
  'u0245': 'Kayıtlar görüntülenebilir; güncel durumu REST üzerinden yeniden alabilirsin.',
  'u0246': 'Bağlantı yokken personel kararı kaydedilemez.',
  'u0247': 'Karar vermeden önce güncel snapshot’ı yeniden al.',
  'u0248': 'Öneri yalnız incelemeyi destekler. Kategori veya birimi değiştirirsen insan karar gerekçesi audit kaydına yazılır.',
  'u0249': 'İç geliştirme yüzeyi',
  'u0250': 'Ctrl+R odak ve shortcut davranışını doğrular. Bu rota yalnız demo ortamındadır.',
  'u0251': 'Eylemler ve alanlar',
  'u0252': 'Kararı doğrula',
  'u0253': 'Durumlar',
  'u0254': 'Harita işaretleri',
  'u0255': 'Sekme, kuyruk ve tablo',
  'u0256': 'Yolda çökme ve şerit daralması',
  'u0257': 'Bildirim alındı',
  'u0258': 'İlgili birime yönlendirildi',
  'u0259': 'Saha değerlendirmesi',
  'u0260': 'Sistem durum yüzeyleri',
  'u0261': 'Henüz kayıt yok',
  'u0262': 'Sunucu geçici olarak yanıt vermedi.',
  'u0263': 'Veri bütünlüğü doğrulanamadı.',
  'u0264': 'Takip no, kategori, kaynak…',
  'u0265': 'Kanıtı, seçim nedenini ve varsa AI override açıklamasını yaz.',
  'u0266': 'Ara',
  'u0267': 'Kategori',
  'u0268': 'Risk',
  'u0269': 'Sorumlu / önerilen birim',
  'u0270': 'Minimum mükerrer ihtimali',
  'u0271': 'Sırala',
  'u0272': 'İBB sorumlu birim',
  'u0273': 'Karar gerekçesi *',
  'u0274': 'Ret / kapsam dışı neden kodu',
  'u0275': 'Vatandaştan istenecek ek bilgi',
  'u0276': 'Birleştirilecek hedef bildirim',
  'u0277': 'İlçe belediyesi',
  'u0278': 'İş gerekçesi',
  'u0279': 'En az 8 karakter; audit kaydına yazılır.',
  'u0280': 'Önceki sayfa',
  'u0281': 'Sonraki sayfa',
  'u0282': 'Önceki kayıt (K)',
  'u0283': 'Sonraki kayıt (J)',
  'u0284': 'Bu kuyruk boş',
  'u0285': 'Bir kayıt seç',
  'u0286': 'Salt okunur inceleme',
  'u0287': 'Karar için incelemeyi üstlen',
  'u0288': 'İnceleme sende',
  'u0289': 'Bildirim ve konum',
  'u0290': 'Lease devralma gerekçesi',
  'u0291': 'Veri kaynağı uyarısı',
  'u0292': 'Format',
  'u0293': 'Fixture içeriği',
  'u0294': 'Gerekçe',
  'u0295': 'İnsan karar gerekçesi',
  'u0296': 'Rol',
  'u0297': 'Kullanıcı, aksiyon, kayıt veya gerekçe ara',
  'u0298': 'Kaynağı yenile',
  'u0299': 'Entegrasyon sınırı',
  'u0300': 'İşlem gerekçesi',
  'u0301': 'Gecikme nedeni',
  'u0302': 'Çözüm açıklaması *',
  'u0303': 'Güvenli sonuç medyası (opsiyonel)',
  'u0304': 'Vatandaş bilgilendirme metni *',
  'u0305': 'Sonuç fotoğrafı opsiyoneldir ve yalnız privacy-safe medya yayımlanabilir.',
  'u0306': 'Yeniden inceleme gerekiyor',
  'u0307': 'Taslak kamuya açık değildir',
  'u0308': 'Analiz henüz yok',
  'u0309': 'Birim görevleri alınamadı.',
  'u0310': 'Vatandaş sorun devam ediyor dedi; otomatik reopen yapılmadı.',
  'u0311': 'Vatandaş “devam ediyor” sinyali verdi. Sistem olayı otomatik olarak yeniden yayımlamadı.',
  'u0312': 'Planlı çalışma verisi alınamadı.',
  'u0313': 'Etki analizi ve vatandaş önizlemesi personel tarafından onaylanmadan sarı pin oluşmaz.',
  'u0314': 'Taslak üzerinde etki analizini çalıştırın.',
  'u0315': 'Bağlantı yok',
  'u0316': 'İşlem tamamlanamadı',
  'u0317': 'Devam edilemiyor',
  'u0318': 'Temizlik ve atık',
  'u0319': 'Park ve yeşil alan',
  'u0320': 'Emin değilim',
  'u0321': 'İBB Kent Takip',
  'u0322': 'Teknik referans: {reference}',
  'u0323': 'Aktif rol: {role}',
  'u0324': 'Bildirim merkezi · {count} okunmamış',
  'u0325': 'Takip numarası: {tracking}',
  'u0326': '{distance} m yakında benzer olay · %{confidence}',
  'u0327': '{step} / {total}',
  'u0328': '{tracking} · {status}',
  'u0329': 'Güncellendi: {date}',
  'u0330': 'Takip no: {tracking}',
  'u0331': 'Talep alındı: {tracking}',
  'u0332': '{tracking} · revizyon {revision}',
  'u0333': '{tracking} doğrulandı ve public olaya dönüştü.',
  'u0334': '{queue} · {total}',
  'u0335': 'Sayfa {page}/{pages}',
  'u0336': '{count} kayıt',
  'u0337': '{tracking} · {category}',
  'u0338': '{tracking} doğrulandı; public olay projection’ı üretildi.',
  'u0339': 'Durum: {status}',
  'u0340': 'Kategori güveni: {value}',
  'u0341': 'Mükerrer güveni: {value}',
  'u0342': 'Neden kodları: {value}',
  'u0343': 'Model: {model} · config: {config}',
  'u0344': 'Sağlık: {health}',
  'u0345': 'Kaynak güncelleme: {date}',
  'u0346': 'Public medya: {count}',
  'u0347': 'Yetkili orijinal medya: {count}',
  'u0348': 'Orijinal medya açılamadı: {error}',
  'u0349': 'Bağlı bildirimler: {value}',
  'u0350': 'Kaynak kayıtları: {value}',
  'u0351': 'Doğrulama sinyalleri: {count}',
  'u0352': 'Bağlı iş referansları: {value}',
  'u0353': 'Sorumlu birim: {unit}',
  'u0354': 'Risk: {risk}',
  'u0355': 'Incident: {incident}',
  'u0356': '{count} güvenli public medya · orijinal medya yayınlanmaz',
  'u0357': '{tracking} · {queue} · {status} · {age} · rev {revision}',
  'u0358': 'WGS84: {lat}, {lon}',
  'u0359': '{incident} · {status}',
  'u0360': '{format} kaynak çıktısı panoya kopyalandı.',
  'u0361': '{role} · {count} izin{unit}',
  'u0362': '{account} için sıradaki izin verilen seviye: {level}',
  'u0363': '{account} rolü',
  'u0364': '{account} kullanıcısının rolü {role} olarak değişecek. Yetkiler rol matrisinden yeniden üretilecek.',
  'u0365': '{kind} audit çıktısı panoya kopyalandı.',
  'u0366': 'Olay {incident}',
  'u0367': '{source}: {workOrder}',
  'u0368': '{media} · privacy-safe',
  'u0369': 'Çalışma: {explanation}',
  'u0370': '{start} – {end}',
  'u0371': 'Çakışma özeti: {count} açıklanabilir kayıt',
  'u0372': '{count} harita kaydı',
  'u0373': '{source} · {verified}',
  'u0374': 'Veri durumu: {freshness}{updated}',
  'u0375': 'Doğrulandı',
  'u0376': 'Doğrulanmadı',
  'u0377': ' · {date}',
  'u0378': 'Birim görevleri',
  'u0379': 'Kullanıcılar',
  'u0380': 'Audit',
  'u0381': 'KVKK',
  'u0382': 'Çukur, çökme, bozuk yüzey',
  'u0383': 'Işık, levha, yol çizgisi',
  'u0384': 'Kaçak, gider, rögar',
  'u0385': 'Çöp, konteyner, moloz',
  'u0386': 'Ağaç, sulama, oyun alanı',
  'u0387': 'Sokak lambası, karanlık alan',
  'u0388': 'AI yalnız öneri sunar; son kararı sen verirsin',
  'u0389': 'Bildirim detayını aç',
  'u0390': 'Fotoğrafsız devam et',
  'u0391': 'Sorun türü',
  'u0392': 'Fotoğraf',
  'u0393': 'Öneriyi kullan',
  'u0394': 'Tahmini inceleme',
  'u0395': 'SLA hedef zamanı',
  'u0396': 'Güncel tahmin',
  'u0397': 'Veri tazeliği',
  'u0398': 'Ek bilgiyi gönder',
  'u0399': 'Sorun görünmüyor',
  'u0400': 'Sorun sürüyor',
  'u0401': 'İnsan incelemesine itiraz gönder',
  'u0402': 'Yeni bildirim oluşturabilir veya diğer filtreleri kontrol edebilirsin.',
  'u0403': 'Durum değişiklikleri burada görünür.',
  'u0404': 'Talep insan incelemesindeyken yeni bildirim gönderimi kapalıdır. Mevcut kayıtların hukuki saklama/anonimleştirme kararı talep iş akışında ele alınır.',
  'u0405': 'Anladım',
  'u0406': 'İnsan incelemesi gerekli',
  'u0407': 'Doğrula ve yayınla',
  'u0408': 'Yeni vatandaş bildirimleri bu kuyrukta görünür.',
  'u0409': 'Birincil eylem',
  'u0410': 'İkincil eylem',
  'u0411': 'Geri döndürülemez',
  'u0412': 'Modal aç',
  'u0413': 'Sheet aç',
  'u0414': 'Adres veya açıklama',
  'u0415': 'Aktif olay',
  'u0416': 'Konum ve açıklama kaydedildi.',
  'u0417': 'Yol Bakım ve Altyapı ekibi inceliyor.',
  'u0418': 'Yeni bir bildirim oluşturduğunda burada görünür.',
  'u0419': 'Güvenlik audit uyarısı',
  'u0420': 'Otomasyon uyarısı',
  'u0421': 'İnsan incelemesi bekleyen gizlilik talebi',
  'u0422': 'Canlı revizyon akışı kesildi',
  'u0423': 'Stale karar engellendi',
  'u0424': 'Komut reddedildi',
  'u0425': 'AI ön analiz · yalnız öneri',
  'u0426': 'Kaynaklar ve güvenilirlik',
  'u0427': 'Medya ve gizlilik',
  'u0428': 'Benzer kayıtlar',
  'u0429': 'Olay çalışma alanı',
  'u0430': 'Public projection önizleme',
  'u0431': 'Belediye operasyon verisi alınamadı.',
  'u0432': 'İnceleme kuyruğu alınamadı.',
  'u0433': 'Lease alınmadan hiçbir belediye kararı çalıştırılmaz.',
  'u0434': 'Bağlantı yokken personel kararları devre dışıdır; son snapshot görüntülenebilir.',
  'u0435': 'Karar vermeden önce REST snapshot yenilemesi yap.',
  'u0436': 'Başka bir istemci daha yeni revizyon yazdı. Güncel snapshot yüklendi; kararı yeniden değerlendir.',
  'u0437': 'Eski kaynak',
  'u0438': 'Kullanılamayan kaynak',
  'u0439': 'En eski inceleme',
  'u0440': 'İlk inceleme medyanı',
  'u0441': 'Yönlendirme medyanı',
  'u0442': 'Çözüm medyanı',
  'u0443': 'Gerekçeyle devral',
  'u0444': 'İncelemeyi üstlen',
  'u0445': 'Bırak',
  'u0446': 'Kaynaklara git',
  'u0447': 'Audit aç',
  'u0448': 'KVKK paneli',
  'u0449': 'Filtreleri değiştir veya başka bir inceleme kuyruğu seç.',
  'u0450': 'Detay, kaynaklar, AI açıklaması ve insan kararları burada açılır. Kısayol: J/K gezin, Enter karar alanına geç, Esc geri dön.',
  'u0451': 'İETT GTFS kartı gerçek şemaya dayalı fixture kanıtıdır; 153 / İstanbul Senin kartı ise gerçek sisteme yazmayan açıkça simüle bir sözleşmedir.',
  'u0452': 'Demo supervisor',
  'u0453': 'Lütfen kısa bir süre bekleyin.',
  'u0454': 'Güncel revizyon {revision} yüklendi. Kararı kontrol edip yeniden gönder.',
  'u0455': '{demoData}. {currentRole}: {role}',
  'u0456': 'Bu kayıt {actor} tarafından {time} saatine kadar inceleniyor.',
  'u0457': 'Lease {time} saatine kadar aktif. Kararlar revision ve audit kontrolünden geçer.',
  'u0458': '{count} kaynak stale, unavailable veya quarantine durumda. Veri kaynakları panelinden provenance ve son hatayı incele.',
  'u0459': '{count} yetki reddi audit kaydı var. Kullanıcıya ayrıntılı güvenlik bilgisi sızdırılmaz; yönetici audit ekranından inceleyebilir.',
  'u0460': '{count} otomatik geçiş başarısız oldu. Olay audit kaydında korunuyor ve insan incelemesi gerekiyor.',
  'u0461': '{count} KVKK/restriction itirazı yönetici kararı bekliyor.',
  'u0462': '{count} çakışma',
  'u0463': '{title}. {message}',
  'u0464': '{title}. {subtitle}. Durum: {status}',
  'u0465': 'İşlem geçmişi, {count} adım',
  'u0466': '{title}. {description}',
  'u0467': '{message}\\\\nTeknik referans: {reference}',
  'u0468': '{label} · {category} · {location}',
  'u0469': '{label}, kategori: {category}, konum: {location}',
  'u0470': '{location} konumunda {count} harita kaydı. Yaklaştır.',
  'u0471': '{title} · {authority}',
  'u0472': 'Yükleniyor',
  'u0473': 'Son alınan veriyi görüntüleyebilirsin; personel işlemleri bağlantı gelene kadar salt okunur.',
  'u0474': 'Taslağın cihazda korunuyor. Bağlantı geldiğinde gönderebilirsin.',
  'u0475': 'Doğrulanmış aktif',
  'u0476': 'Doğrulama bekliyor',
  'u0477': 'Kritik inceleme',
  'u0478': 'İnceleme sonrası atanacak',
  'u0479': 'tahmindir, garanti değildir',
  'u0480': 'hedef, garanti değildir',
  'u0481': 'garanti değildir',
  'u0482': 'Sonuç fotoğrafı gizlilik kontrolünden geçirilerek yayımlandı.',
  'u0483': 'Saha sorumlusu',
  'u0484': 'Saha ekibi',
  'u0485': 'SLA hedef aralığı',
  'u0486': 'Saha atamasında başlar',
  'u0487': 'Yeni tahmin',
  'u0488': 'Atanmadı',
  'u0489': 'Fotoğraf çek',
  'u0490': 'Yeniden çek',
  'u0491': 'Fotoğraf yok',
  'u0492': 'Kamusal önizleme güvenli',
  'u0493': 'Kamusal gösterim kapalı; insan kontrolü gerekli',
  'u0494': 'AI ön analiz önerisi',
  'u0495': 'AI kısmi/erişilemez',
  'u0496': 'Otomatik öneri alınamadı; bildirim insan incelemesine gidecek.',
  'u0497': 'Önerilen tür: {category} · Güven: %{confidence}',
  'u0498': 'İstanbul sınırları içinde geçerli bir konum seç.',
  'u0499': 'Açıklama en az 10 karakter olmalıdır.',
  'u0500': 'Kesilen kamera işlemi güvenle geri yüklendi.',
  'u0501': 'Mevcut olay doğrulandı',
  'u0502': 'Gönderilemedi; taslak ve fotoğraf cihazda korunuyor.',
  'u0503': 'Tür',
  'u0504': 'Fotoğraf',
  'u0505': 'Konum',
  'u0506': 'Detay',
  'u0507': 'Kontrol',
  'u0508': 'Onayla ve gönder',
  'u0509': 'Fotoğrafa geç',
  'u0510': 'Devam et',
  'u0511': '{label} (tahmindir, garanti değildir)',
  'u0512': 'Benzer olayla birleştirildi',
  'u0513': 'İnceleme notu',
  'u0514': 'Durum kaydı güvenle işlendi.',
  'u0515': 'Ek bilgi kaydedildi ve inceleme kuyruğuna iletildi.',
  'u0516': 'Geri bildirimin alındı.',
  'u0517': 'İtirazın insan incelemesi için kaydedildi.',
  'u0518': 'Bildirim alındı',
  'u0519': 'Ön analiz',
  'u0520': 'İncelemede',
  'u0521': 'Ek bilgi bekleniyor',
  'u0522': 'İlgili birime yönlendirildi',
  'u0523': 'Sahada işlemde',
  'u0524': 'Çözüldü',
  'u0525': 'Birleştirildi',
  'u0526': 'Kapsam dışı',
  'u0527': 'Reddedildi',
  'u0528': 'Ön kontroller tamamlandı ve ilgili birime yönlendirildi',
  'u0529': 'Ek bilgi alındı',
  'u0530': 'Çözüm geri bildirimi alındı',
  'u0531': 'İtiraz alındı',
  'u0532': 'Durum güncellendi',
  'u0533': 'Bildirim durumu değişti',
  'u0534': 'Ek bilgi isteniyor',
  'u0535': 'Çözüm yayımlandı',
  'u0536': 'Kent Takip bildirimi',
  'u0537': 'Verilerime erişim',
  'u0538': 'Düzeltme talebi',
  'u0539': 'Veri silme talebi',
  'u0540': 'Otomatik değerlendirmeye itiraz',
  'u0541': 'Gelen bildirimleri, olayları ve veri sağlığını tek bakışta izleyin.',
  'u0542': 'İnsan incelemesi',
  'u0543': 'Kanıtı ve yönlendirme gerekçesini yaz',
  'u0544': 'Karar gerekçesi zorunludur.',
  'u0545': 'Rol bazlı menü izolasyonu',
  'u0546': 'Güvenli derin bağlantı',
  'u0547': 'Uyarlanabilir çalışma alanı',
  'u0548': 'Sentetik demo verisi',
  'u0549': 'Doğrulanmış bilgi',
  'u0550': 'Gizlilik odaklı',
  'u0551': 'Hazır',
  'u0552': 'Klavye ile yenilendi',
  'u0553': 'Örn. Meşrutiyet Caddesi',
  'u0554': 'Planlanan',
  'u0555': 'Kritik inceleme',
  'u0556': 'Takip no',
  'u0557': 'Birim',
  'u0558': 'Durum',
  'u0559': 'Yönlendirildi',
  'u0560': 'Bugün, 10:42',
  'u0561': 'Bugün, 11:03',
  'u0562': 'Bekleniyor.',
  'u0563': 'Parolayı göster',
  'u0564': 'Parolayı gizle',
  'u0565': 'Açıklama bu snapshot’ta ayrı alan olarak bulunmuyor.',
  'u0566': 'Personel inceleme çalışma alanından çıktı.',
  'u0567': 'Neden bu incelemeyi devralıyorsun?',
  'u0568': 'Public preview insan onayı olmadan yayınlanamaz.',
  'u0569': 'Ek bilgi mesajı zorunludur.',
  'u0570': 'Kritik kaydı kapatma',
  'u0571': 'Kritik sinyal içeren bu kaydı {action} istediğine emin misin?',
  'u0572': 'Kaynak',
  'u0573': 'Hedef',
  'u0574': 'Kritik',
  'u0575': 'Yüksek öncelik',
  'u0576': 'Normal',
  'u0577': 'Düşük güven',
  'u0578': 'Gizlilik',
  'u0579': 'Kötüye kullanım',
  'u0580': 'Manuel / AI hata',
  'u0581': 'Öncelik + en eski',
  'u0582': 'En eski',
  'u0583': 'En yeni',
  'u0584': 'Mükerrer olasılığı',
  'u0585': 'ret',
  'u0586': 'kapsam dışına almak',
  'u0587': 'ek bilgi istemek',
  'u0588': 'birleştirmek',
  'u0589': 'İBB’ye yönlendirmek',
  'u0590': 'ilçeye yönlendirmek',
  'u0591': 'geri aktarmak',
  'u0592': 'kilitli',
  'u0593': 'Güncel',
  'u0594': 'Gecikmiş',
  'u0595': 'Karantina',
  'u0596': 'Kapalı',
  'u0597': 'Kullanılamıyor',
  'u0598': 'Saha teyidi ile yetkili belediye girişi',
  'u0599': 'Yetkili insan incelemesiyle talep kabul edildi.',
  'u0600': 'Yetkili insan incelemesiyle gerekçeli olarak reddedildi.',
  'u0601': 'Misafir',
  'u0602': 'Vatandaş',
  'u0603': 'İnceleyici',
  'u0604': 'Birim sorumlusu',
  'u0605': 'Planlamacı',
  'u0606': 'Sistem yöneticisi',
  'u0607': 'Demo sorumlusu',
  'u0608': 'Operasyon güncellemesi',
  'u0609': 'Saha erişimi gecikti',
  'u0610': 'Atanmamış',
  'u0611': 'Bana atanmış',
  'u0612': 'Saha ekibinde',
  'u0613': 'Devam ediyor',
  'u0614': 'Süresi aşan',
  'u0615': 'Planlı yol bakım çalışması',
  'u0616': 'Geçerli alanlar tamamlanınca taslak otomatik kaydedilir.',
  'u0617': 'Taslak {id} otomatik kaydediliyor.',
  'u0618': '1. Çalışma türü',
  'u0619': '2. Konum · enlem',
  'u0620': 'Konum · boylam',
  'u0621': '3. Etkilenen alan yarıçapı (m)',
  'u0622': '4. Başlangıç (UTC ISO-8601)',
  'u0623': 'Tahmini bitiş (UTC ISO-8601)',
  'u0624': '5. Sorumlu birim',
  'u0625': '6. Açıklama',
  'u0626': 'Kaydediliyor…',
  'u0627': 'Taslağı kaydet',
  'u0628': 'Taslak etki merkezi · public değil',
  'u0629': 'Personel taslak önizlemesi',
  'u0630': '{label}, işlem sürüyor',
  'u0631': 'Tamamlandı',
  'u0632': 'Bekliyor',
  'u0633': 'Aktif olay',
  'u0634': 'İtiraz',
  'u0635': 'reddetmek',
  'u0636': 'kapsam dışına almak',
  'u0637': 'Durum kaydı',
  'u0638': 'Saat',
  'u0639': '{days}g {hours}sa',
  'u0640': '{hours}sa {minutes}dk',
  'u0641': '{minutes}dk',
  'u0642': '{distance} km',
  'u0643': '{distance} m',
  'u0644': '{tracking}: {decision} kaydedildi.',

  'u0645': 'Eklenmedi',
  'u0646': 'Metadata temizlendi',
  'u0647': 'Geri',
  'u0648': 'Aktif',
  'u0649': 'Tümü',
  'u0650': 'Beyoğlu',
  'u0651': 'Meşrutiyet Caddesi, Şişhane',

  'u0652': 'Sayfa bulunamadı',
  'u0653': 'Alım',

  'u0654': '+90 555 000 11 22',

  'u0655': 'Demo kodu: {code}',
  'u0656': '{message} {seconds} sn.',
  'u0657': 'Sentetik demo',
  'u0658': 'AI: {ai} · Gizlilik: {privacy} · {connectivity}',
  'u0659': 'operasyon',
  'u0660': 'rol',
  'u0661': 'itiraz',
  'u0662': 'Otorite',

  'u0663': 'Yenile',
  'u0664': 'Kamera izni reddedildi. Ayarlardan izin verebilir veya fotoğrafsız devam edebilirsin.',
  'u0665': 'Kamera bu cihazda kısıtlanmış. Fotoğrafsız devam edebilirsin.',
  'u0666': 'Bu cihazda kullanılabilir kamera bulunamadı.',
  'u0667': 'Kamera işlemi tamamlanamadı.',
  'u0668': 'Fotoğraf 8 MB sınırını aşmamalıdır.',
  'u0669': 'Kamera işlemi iptal edildi.',
  'u0670': 'Fotoğraf biçimi güvenli biçimde işlenemedi.',
  'u0671': 'İşlem güvenli biçimde tamamlanamadı. Teknik kod: {code}',

  'u0672': 'Pilot KPI ve ROI',
  'u0673': 'Yalnız demo/pilot olaylarından türetilir. Üretim sonucu veya tasarruf iddiası değildir.',
  'u0674': 'North-star oranı',
  'u0675': 'Medyan ilk insan inceleme',
  'u0676': 'İlk seferde yönlendirme',
  'u0677': 'Tekil olay başına mükerrer kayıt',
  'u0678': 'Personel AI override oranı',
  'u0679': 'Hedef sürede çözüm',
  'u0680': 'Tekrar durum sorma oranı',
  'u0681': 'Çözüm doğrulama oranı',
  'u0682': 'Yeterli veri yok',
  'u0683': 'ROI hesaplayıcı',
  'u0684': 'Bütün girdiler girilmeden parasal sonuç hesaplanmaz.',
  'u0685': 'Baseline triage dakikası',
  'u0686': 'Pilot triage dakikası',
  'u0687': 'Aylık başvuru',
  'u0688': 'Personel dakika maliyeti',
  'u0689': 'Baseline yanlış yönlendirme',
  'u0690': 'Pilot yanlış yönlendirme',
  'u0691': 'Yeniden işlem maliyeti',
  'u0692': 'Baseline mükerrer kayıt',
  'u0693': 'Pilot mükerrer kayıt',
  'u0694': 'Kayıt başına işlem maliyeti',
  'u0695': 'Baseline durum sorma',
  'u0696': 'Pilot durum sorma',
  'u0697': 'Durum sorma çağrı maliyeti',
  'u0698': 'Altyapı maliyeti',
  'u0699': 'AI maliyeti',
  'u0700': 'Harita maliyeti',
  'u0701': 'SMS maliyeti',
  'u0702': 'Destek maliyeti',
  'u0703': 'Operasyon maliyeti',
  'u0704': 'Hesapla',
  'u0705': 'Aylık brüt operasyon kazancı',
  'u0706': 'Aylık işletim maliyeti',
  'u0707': 'Aylık net etki',
  'u0708': '7 dakikalık jüri rotası',
  'u0709': 'Kontrol merkezi',
  'u0710': 'DemoClock +15 dk',
  'u0711': 'DemoClock +1 saat',
  'u0712': 'Kaynak kesintisini simüle et',
  'u0713': 'Kaynağı toparla',
  'u0714': 'AI başarısızlığını simüle et',
  'u0715': 'AI normal moda dön',
  'u0716': 'Bu kontrol için Demo Supervisor oturumu gerekir.',
  'u0717': 'Demo kontrolü uygulandı.',
  'u0718': 'Tekrar durum bilgisi iste',
  'u0719': 'Durum isteğin kaydedildi; öncelik otomatik değiştirilmedi.',
  'u0720': 'Pilot hedefleri hipotezdir; başarılmış sonuç gibi sunulmaz.',
  'u0721': 'İncelenen kayıt',
  'u0722': 'Yönlendirilen kayıt',
  'u0723': 'Çözülen olay',
  'u0724': 'Çözüm geri bildirimi',
  'u0725': 'Durum isteği',
  'u0726': 'Adım {index}: {start}–{end} sn',
  'u0727': 'Beklenen kanıt: {evidence}',
  'u0728': 'DemoClock ofseti: {minutes} dk',
  'u0729': 'AI modu: {mode}',
  'u0730': 'KPI formülleri snapshot ve immutable audit olaylarından hesaplanır.',
  'u0731': 'ROI formülü gerçek pilot girdileri ister; boş değerler sıfır kabul edilmez.',
  'u0732': 'Girdileri temizle',
  'u0733': 'Geçersiz veya eksik ROI girdisi var.',
  'u0734': 'Pilot karar şablonu',
  'u0735': 'Baseline, hedef ve go/no-go kanıtı release paketindeki şablonda tutulur.',

  'u0736': 'Shared modda DemoClock sunucu saatini değiştirmez; bu kontrol yalnız local demo için etkindir.',
  'u0737': 'Problem ve mevcut sistemle fark',
  'u0738': '153 ve İstanbul Senin giriş kanalıdır; Kent Takip ortak olay katmanıdır.',
  'u0739': 'Ortak kent görünümü',
  'u0740': 'Doğrulanmış olay, planlı çalışma, kaynak/güncellik ve erişilebilir listeyi göster.',
  'u0741': 'Vatandaş bildirimi',
  'u0742': 'Gizlilik-safe medya, konum, benzer olay ve kontrollü doğrulama akışını göster.',
  'u0743': 'AI sınırı',
  'u0744': 'AI yalnız öneri verir; ret, yaptırım ve kamuya yayın insan kararıdır.',
  'u0745': 'Belediye olay çalışma alanı',
  'u0746': 'Çoklu sinyal, kaynak, gizlilik sonucu ve insan doğrulama/yönlendirmesini göster.',
  'u0747': 'Kapalı döngü',
  'u0748': 'Takip numarasını, timeline güncellemesini ve çözüm kanıtını göster.',
  'u0749': 'Kaynak kesintisi ve güven',
  'u0750': 'Gerçek şema kanıtını, stale/unavailable fallback ve auditli medya erişimini göster.',
  'u0751': 'Ölçüm, pilot ve talep',
  'u0752': 'North-star, 6 haftalık pilot, formül tabanlı ROI ve tek pilot talebini göster.',
  'u0753': 'Demo verisini sıfırla',
  'u0754': 'Yakınlaştır',
  'u0755': 'Uzaklaştır',
  'u0756': 'Harita görünümüne dön',
  'u0757': 'Harita {place} konumuna odaklandı.',

};

const Map<String, String> appTextEn = {
  'u0001': 'Preparing demo',
  'u0002': 'Demo data could not be opened',
  'u0003': 'Local startup data could not be loaded safely. ',
  'u0004': 'Try again',
  'u0005': 'Your report was received',
  'u0006': 'What kind of issue is this?',
  'u0007': 'Choose the best matching type. You can change the suggestion after photo analysis.',
  'u0008': 'Add a photo',
  'u0009': 'Show the issue from a safe location without approaching it, preferably in a single frame.',
  'u0010': 'Photo quality and format checked',
  'u0011': 'EXIF and additional metadata removed',
  'u0012': 'Human privacy review is required for faces/license plates',
  'u0013': 'No public copy is created until the review is complete.',
  'u0014': 'Confirm the location',
  'u0015': 'Check the suggested location or adjust the coordinates manually.',
  'u0016': 'Add a short description',
  'u0017': 'Describe what you saw and any safe approach information. Do not include personal information.',
  'u0018': 'Review and submit',
  'u0019': 'Confirm an existing incident',
  'u0020': 'Create a new report',
  'u0021': 'By submitting, you agree that if a blurred/safe public preview cannot be produced, the photo will be visible only to authorized staff.',
  'u0022': 'Report an issue',
  'u0023': 'My reports',
  'u0024': 'Active',
  'u0025': 'Completed',
  'u0026': 'All',
  'u0027': 'Activity history',
  'u0028': 'Photo you submitted',
  'u0029': 'The original image is not included in the public response.',
  'u0030': 'Resolution feedback',
  'u0031': 'Choosing “The issue persists” does not reopen the case automatically; it creates a human review signal.',
  'u0032': 'Notification center',
  'u0033': 'Unread only',
  'u0034': 'Privacy rights',
  'u0035': 'Access, correction, deletion, and objection-to-automated-assessment requests are recorded with a tracking number and sent for human review.',
  'u0036': 'Usage restriction',
  'u0037': 'Under review',
  'u0038': 'Appeal',
  'u0039': 'Delete account',
  'u0040': 'Create account deletion request',
  'u0041': 'This action requires re-authentication and an explicit second confirmation.',
  'u0042': 'Start',
  'u0043': 'Cancel',
  'u0044': 'Submit',
  'u0045': 'Re-authentication',
  'u0046': 'Verify',
  'u0047': 'Confirm account deletion request',
  'u0048': 'After the request is opened, you cannot submit new reports. Deletion/anonymization of existing records is handled by a human through the privacy workflow.',
  'u0049': 'Create request',
  'u0050': 'Appeal restriction',
  'u0051': 'Roads and sidewalks',
  'u0052': 'Traffic and signals',
  'u0053': 'Water and infrastructure',
  'u0054': 'Lighting',
  'u0055': 'Road Maintenance and Infrastructure',
  'u0056': 'Traffic Directorate',
  'u0057': 'Water Operations',
  'u0058': 'This action creates a red public incident. AI cannot perform this action on its own.',
  'u0059': 'Review queues',
  'u0060': 'Component gallery',
  'u0061': 'The dialog keeps focus in a closed loop and returns it to the invoking control when closed.',
  'u0062': 'Close',
  'u0063': 'Mobile secondary action surface; respects safe areas and keyboard insets.',
  'u0064': 'Components',
  'u0065': 'Demo reset requires the resetDemo permission.',
  'u0066': 'In shared demo mode, reset is available only to the server administrator.',
  'u0067': 'Municipal operations center',
  'u0068': 'Queue counts are derived live from snapshot domain data; critical records are not lost under the normal queue.',
  'u0069': 'Priority reviews',
  'u0070': 'There are no open review records right now.',
  'u0071': 'Back to queue',
  'u0072': 'Filters',
  'u0073': 'Road surface damage',
  'u0074': 'Traffic sign / signal',
  'u0075': 'Water infrastructure',
  'u0076': 'Beyoglu Municipality',
  'u0077': 'Uskudar Municipality',
  'u0078': '%25+',
  'u0079': '%50+',
  'u0080': '%75+',
  'u0081': 'Clear filters',
  'u0082': 'Search and filters',
  'u0083': 'Human decision',
  'u0084': 'AI only provides suggestions; the actions below run only through an authorized human command.',
  'u0085': 'Insufficient / unverifiable evidence',
  'u0086': 'Outside municipal responsibility',
  'u0087': 'Private property / private responsibility',
  'u0088': 'Outside service / authority scope',
  'u0089': 'Invalid / abuse',
  'u0090': 'I reviewed the public preview as a human',
  'u0091': 'Verification creates a red public incident; original media never enters the public projection.',
  'u0092': 'Verify + publish',
  'u0093': 'Reject',
  'u0094': 'Out of scope',
  'u0095': 'Change IBB unit',
  'u0096': 'Undo incorrect routing',
  'u0097': 'Request more information',
  'u0098': 'Select target',
  'u0099': 'Merge report',
  'u0100': 'Demo district municipality',
  'u0101': 'Route to district municipality',
  'u0102': 'Take over',
  'u0103': 'Approve',
  'u0104': 'No AI result. The record will be handled by manual review.',
  'u0105': 'No linked institutional source record.',
  'u0106': 'Source health signals conflict with each other.',
  'u0107': 'A business justification is required to open original content; every access is written to the immutable audit log.',
  'u0108': 'Open with justification',
  'u0109': 'Original media is hidden for this role.',
  'u0110': 'Original media access',
  'u0111': 'Access',
  'u0112': 'No clear nearby merge candidate in the same category.',
  'u0113': 'No citizen-visible timeline event.',
  'u0114': 'Authorized audit',
  'u0115': 'No linked UrbanIncident yet. It can be created by verification or merge.',
  'u0116': 'Merge comparison',
  'u0117': 'Data sources',
  'u0118': 'Source status, source timestamp, and ingestion time are shown separately. Stale data is never presented as current.',
  'u0119': 'Run GTFS schema proof',
  'u0120': 'Authorized manual incident',
  'u0121': '153 contract simulation',
  'u0122': 'Import JSON/CSV fixture',
  'u0123': 'Export JSON',
  'u0124': 'Export CSV',
  'u0125': 'Source',
  'u0126': 'API / CSV',
  'u0127': 'Status',
  'u0128': 'Last successful ingestion',
  'u0129': 'Source time',
  'u0130': 'Ingestion time',
  'u0131': 'Accepted / Quarantined',
  'u0132': 'Last error',
  'u0133': 'Action',
  'u0134': 'Validated fixture import',
  'u0135': 'JSON',
  'u0136': 'CSV',
  'u0137': 'Validate and import',
  'u0138': 'Save',
  'u0139': 'User and role management',
  'u0140': 'Critical role/permission changes require a second approval and become immutable audit events.',
  'u0141': 'Edit role and permissions',
  'u0142': 'Progressive usage restriction',
  'u0143': 'Save decision',
  'u0144': 'Continue',
  'u0145': 'Second approval',
  'u0146': 'Immutable audit explorer',
  'u0147': 'Audit events cannot be changed or deleted from this screen; they can only be filtered and exported.',
  'u0148': 'Copy CSV',
  'u0149': 'Copy JSON',
  'u0150': 'No audit events match this filter.',
  'u0151': 'Privacy and security requests',
  'u0152': 'Access, correction, deletion, and objection-to-automated-assessment requests are closed by a human decision.',
  'u0153': 'No open privacy request.',
  'u0154': 'Accept',
  'u0155': 'Reject with reason',
  'u0156': 'Usage restrictions and appeals',
  'u0157': 'No active or past restriction record.',
  'u0158': 'RBAC permission matrix',
  'u0159': 'Reviewer · Unit · Planner · System Admin · Demo Supervisor',
  'u0160': 'Unit tasks and field resolution',
  'u0161': 'SLA is a target range; citizen screens never present it as a guarantee.',
  'u0162': 'Offline · read-only',
  'u0163': 'No tasks match this filter.',
  'u0164': 'No field tasks match this filter.',
  'u0165': 'SLA target exceeded',
  'u0166': 'Assign to field team',
  'u0167': 'Start field work',
  'u0168': 'Save delay and new estimate',
  'u0169': 'Add photo',
  'u0170': 'Mark as resolved',
  'u0171': 'Work planning',
  'u0172': '7. Run impact analysis',
  'u0173': 'Draft could not be saved; check fields and connection.',
  'u0174': 'No planned work found.',
  'u0175': 'Explainable impact analysis',
  'u0176': 'Impact map',
  'u0177': 'Timeline',
  'u0178': 'Planned start',
  'u0179': 'Estimated end',
  'u0180': 'Affected roads and lines',
  'u0181': 'Conflict explanations',
  'u0182': 'Rule-based alternatives',
  'u0183': 'Citizen information draft',
  'u0184': 'Send to publish review',
  'u0185': 'Publishing review',
  'u0186': 'This preview approximates the citizen view. The yellow pin is published only after human approval.',
  'u0187': 'Planned work',
  'u0188': 'Source summary: demo road/transit buffers + planned municipal work time windows',
  'u0189': 'I reviewed the public preview and required fields as a human',
  'u0190': 'Impact analysis is not a forecast; geometry/time conflicts and the demo references used are explained.',
  'u0191': 'Work was published as a yellow planned pin.',
  'u0192': 'Publish work',
  'u0193': 'Planned',
  'u0194': 'Traffic',
  'u0195': '© OpenStreetMap contributors',
  'u0197': 'Local startup data could not be loaded safely. Try again or close the application.',
  'u0196': 'No records to show for this filter.',
  'u0198': 'Search district, neighborhood, or address',
  'u0199': 'Clear search',
  'u0200': 'Show all Istanbul',
  'u0201': 'Search this area',
  'u0202': 'Accessible list',
  'u0203': 'Map view',
  'u0204': 'Istanbul urban incidents map. The same content is available with the list button.',
  'u0205': 'Offline map',
  'u0206': 'Map tiles could not be loaded; records are shown on the local fallback map.',
  'u0207': 'E.g. There is a deep road depression in the right lane.',
  'u0208': 'Latitude',
  'u0209': 'Longitude',
  'u0210': 'Description',
  'u0211': 'Human review safeguard',
  'u0212': 'AI output is preliminary analysis only. Authorized staff decide publication and routing.',
  'u0213': 'This step could not be completed',
  'u0214': 'Your privacy is protected',
  'u0215': 'Camera information',
  'u0216': 'Location visibility',
  'u0217': 'AI preliminary analysis',
  'u0218': 'Photo metadata is removed; if faces or plates cannot be handled safely, the image is not made public.',
  'u0219': 'Sensitive locations are approximated in public view while the authorized review record is preserved.',
  'u0220': 'A category, routing unit, and possible similar record may be suggested. The final decision belongs to you and the authorized reviewer.',
  'u0221': 'Requested additional information',
  'u0222': 'Appeal explanation',
  'u0223': 'Offline view',
  'u0224': 'The last synced state is shown; new drafts remain on the device.',
  'u0225': 'No reports in this filter',
  'u0226': 'Source may be stale',
  'u0227': 'Resolution evidence',
  'u0228': 'Operation result',
  'u0229': 'Report not found',
  'u0230': 'The report was not found or does not belong to this account.',
  'u0231': 'The latest source sync may be delayed; the activity history is the canonical record.',
  'u0232': 'Request description',
  'u0233': 'Demo verification code',
  'u0234': 'Appeal reason',
  'u0235': 'Verified category',
  'u0236': 'Responsible unit',
  'u0237': 'Demo code: 123456',
  'u0238': 'Live update disconnected',
  'u0239': 'Deletion request received',
  'u0240': 'No report awaiting review',
  'u0241': 'Read-only mode',
  'u0242': 'Record changed in another client',
  'u0243': 'AI preliminary analysis available',
  'u0244': 'Map data could not be loaded.',
  'u0245': 'Records remain viewable; refresh the current state over REST.',
  'u0246': 'Staff decisions cannot be saved while offline.',
  'u0247': 'Refresh the current snapshot before making a decision.',
  'u0248': 'The suggestion only supports review. If you change the category or unit, the human decision reason is written to the audit record.',
  'u0249': 'Internal development surface',
  'u0250': 'Ctrl+R verifies focus and shortcut behavior. This route exists only in the demo environment.',
  'u0251': 'Actions and fields',
  'u0252': 'Confirm decision',
  'u0253': 'States',
  'u0254': 'Map markers',
  'u0255': 'Tabs, queue, and table',
  'u0256': 'Road depression and lane narrowing',
  'u0257': 'Report received',
  'u0258': 'Routed to responsible unit',
  'u0259': 'Field assessment',
  'u0260': 'System state surfaces',
  'u0261': 'No records yet',
  'u0262': 'The server did not respond temporarily.',
  'u0263': 'Data integrity could not be verified.',
  'u0264': 'Tracking no., category, source…',
  'u0265': 'Write the evidence, selection rationale, and AI override explanation if applicable.',
  'u0266': 'Search',
  'u0267': 'Category',
  'u0268': 'Risk',
  'u0269': 'Responsible / suggested unit',
  'u0270': 'Minimum duplicate likelihood',
  'u0271': 'Sort',
  'u0272': 'IMM responsible unit',
  'u0273': 'Decision reason *',
  'u0274': 'Rejection / out-of-scope reason code',
  'u0275': 'Additional information to request from citizen',
  'u0276': 'Target report to merge',
  'u0277': 'District municipality',
  'u0278': 'Business reason',
  'u0279': 'At least 8 characters; written to the audit record.',
  'u0280': 'Previous page',
  'u0281': 'Next page',
  'u0282': 'Previous record (K)',
  'u0283': 'Next record (J)',
  'u0284': 'This queue is empty',
  'u0285': 'Select a record',
  'u0286': 'Read-only review',
  'u0287': 'Take ownership of review',
  'u0288': 'Review assigned to you',
  'u0289': 'Report and location',
  'u0290': 'Lease takeover reason',
  'u0291': 'Data source warning',
  'u0292': 'Format',
  'u0293': 'Fixture content',
  'u0294': 'Reason',
  'u0295': 'Human decision reason',
  'u0296': 'Role',
  'u0297': 'Search user, action, record, or reason',
  'u0298': 'Refresh source',
  'u0299': 'Integration boundary',
  'u0300': 'Operation reason',
  'u0301': 'Delay reason',
  'u0302': 'Resolution description *',
  'u0303': 'Safe result media (optional)',
  'u0304': 'Citizen information text *',
  'u0305': 'A result photo is optional and only privacy-safe media may be published.',
  'u0306': 'Re-review required',
  'u0307': 'Draft is not public',
  'u0308': 'Analysis not available yet',
  'u0309': 'Unit tasks could not be loaded.',
  'u0310': 'The citizen said the issue persists; it was not reopened automatically.',
  'u0311': 'The citizen signaled that the issue persists. The system did not republish the incident automatically.',
  'u0312': 'Planned work data could not be loaded.',
  'u0313': 'A yellow pin is not created until staff approve the impact analysis and citizen preview.',
  'u0314': 'Run impact analysis on the draft.',
  'u0315': 'Offline',
  'u0316': 'Operation failed',
  'u0317': 'Cannot continue',
  'u0318': 'Cleaning and waste',
  'u0319': 'Parks and green spaces',
  'u0320': 'Not sure',
  'u0321': 'IMM Urban Tracker',
  'u0322': 'Technical reference: {reference}',
  'u0323': 'Active role: {role}',
  'u0324': 'Notification center · {count} unread',
  'u0325': 'Tracking number: {tracking}',
  'u0326': 'Similar incident {distance} m away · {confidence}%',
  'u0327': '{step} / {total}',
  'u0328': '{tracking} · {status}',
  'u0329': 'Updated: {date}',
  'u0330': 'Tracking no.: {tracking}',
  'u0331': 'Request received: {tracking}',
  'u0332': '{tracking} · revision {revision}',
  'u0333': '{tracking} was verified and converted to a public incident.',
  'u0334': '{queue} · {total}',
  'u0335': 'Page {page}/{pages}',
  'u0336': '{count} records',
  'u0337': '{tracking} · {category}',
  'u0338': '{tracking} was verified; the public incident projection was created.',
  'u0339': 'Status: {status}',
  'u0340': 'Category confidence: {value}',
  'u0341': 'Duplicate confidence: {value}',
  'u0342': 'Reason codes: {value}',
  'u0343': 'Model: {model} · config: {config}',
  'u0344': 'Health: {health}',
  'u0345': 'Source update: {date}',
  'u0346': 'Public media: {count}',
  'u0347': 'Authorized original media: {count}',
  'u0348': 'Original media could not be opened: {error}',
  'u0349': 'Linked reports: {value}',
  'u0350': 'Source records: {value}',
  'u0351': 'Verification signals: {count}',
  'u0352': 'Linked work references: {value}',
  'u0353': 'Responsible unit: {unit}',
  'u0354': 'Risk: {risk}',
  'u0355': 'Incident: {incident}',
  'u0356': '{count} safe public media · original media is never published',
  'u0357': '{tracking} · {queue} · {status} · {age} · rev {revision}',
  'u0358': 'WGS84: {lat}, {lon}',
  'u0359': '{incident} · {status}',
  'u0360': '{format} source output copied to clipboard.',
  'u0361': '{role} · {count} permissions{unit}',
  'u0362': 'Next allowed level for {account}: {level}',
  'u0363': 'Role for {account}',
  'u0364': 'The role of {account} will change to {role}. Permissions will be regenerated from the role matrix.',
  'u0365': '{kind} audit output copied to clipboard.',
  'u0366': 'Incident {incident}',
  'u0367': '{source}: {workOrder}',
  'u0368': '{media} · privacy-safe',
  'u0369': 'Work: {explanation}',
  'u0370': '{start} – {end}',
  'u0371': 'Conflict summary: {count} explainable records',
  'u0372': '{count} map records',
  'u0373': '{source} · {verified}',
  'u0374': 'Data status: {freshness}{updated}',
  'u0375': 'Verified',
  'u0376': 'Unverified',
  'u0377': ' · {date}',
  'u0378': 'Unit tasks',
  'u0379': 'Users',
  'u0380': 'Audit',
  'u0381': 'Privacy requests',
  'u0382': 'Pothole, depression, damaged surface',
  'u0383': 'Signal light, sign, road marking',
  'u0384': 'Leak, drain, manhole',
  'u0385': 'Waste, container, debris',
  'u0386': 'Tree, irrigation, playground',
  'u0387': 'Street light, dark area',
  'u0388': 'AI only suggests; you make the final decision',
  'u0389': 'Open report details',
  'u0390': 'Continue without photo',
  'u0391': 'Issue type',
  'u0392': 'Photo',
  'u0393': 'Use suggestion',
  'u0394': 'Estimated review',
  'u0395': 'SLA target time',
  'u0396': 'Current estimate',
  'u0397': 'Data freshness',
  'u0398': 'Send additional information',
  'u0399': 'Issue no longer visible',
  'u0400': 'Issue persists',
  'u0401': 'Submit appeal for human review',
  'u0402': 'You can create a new report or check other filters.',
  'u0403': 'Status changes appear here.',
  'u0404': 'New report submission is disabled while the request is under human review. Legal retention or anonymization of existing records is handled in the request workflow.',
  'u0405': 'Got it',
  'u0406': 'Human review required',
  'u0407': 'Verify and publish',
  'u0408': 'New citizen reports appear in this queue.',
  'u0409': 'Primary action',
  'u0410': 'Secondary action',
  'u0411': 'Irreversible',
  'u0412': 'Open modal',
  'u0413': 'Open sheet',
  'u0414': 'Address or description',
  'u0415': 'Active incident',
  'u0416': 'Location and description were saved.',
  'u0417': 'The Road Maintenance and Infrastructure team is reviewing it.',
  'u0418': 'A new report will appear here after you create it.',
  'u0419': 'Security audit alert',
  'u0420': 'Automation alert',
  'u0421': 'Privacy request awaiting human review',
  'u0422': 'Live revision stream disconnected',
  'u0423': 'Stale decision blocked',
  'u0424': 'Command rejected',
  'u0425': 'AI preliminary analysis · suggestion only',
  'u0426': 'Sources and reliability',
  'u0427': 'Media and privacy',
  'u0428': 'Similar records',
  'u0429': 'Incident workspace',
  'u0430': 'Public projection preview',
  'u0431': 'Municipal operations data could not be loaded.',
  'u0432': 'Review queue could not be loaded.',
  'u0433': 'No municipal decision can run without acquiring the review lease.',
  'u0434': 'Staff decisions are disabled while offline; the last snapshot remains viewable.',
  'u0435': 'Refresh the REST snapshot before making a decision.',
  'u0436': 'Another client wrote a newer revision. The current snapshot was loaded; reassess the decision.',
  'u0437': 'Stale source',
  'u0438': 'Unavailable source',
  'u0439': 'Oldest review',
  'u0440': 'Median first review',
  'u0441': 'Median routing',
  'u0442': 'Median resolution',
  'u0443': 'Take over with reason',
  'u0444': 'Take review',
  'u0445': 'Release',
  'u0446': 'Go to sources',
  'u0447': 'Open audit',
  'u0448': 'Privacy panel',
  'u0449': 'Change the filters or select another review queue.',
  'u0450': 'Details, sources, AI explanation, and human decisions open here. Shortcuts: J/K navigate, Enter moves to the decision area, Esc goes back.',
  'u0451': 'The IETT GTFS card is fixture evidence based on a real schema; the 153 / Istanbul Senin card is an explicitly simulated contract that does not write to the real system.',
  'u0452': 'Demo supervisor',
  'u0453': 'Please wait briefly.',
  'u0454': 'Revision {revision} was loaded. Review the decision and submit it again.',
  'u0455': '{demoData}. {currentRole}: {role}',
  'u0456': 'This record is being reviewed by {actor} until {time}.',
  'u0457': 'The lease is active until {time}. Decisions pass revision and audit checks.',
  'u0458': '{count} sources are stale, unavailable, or quarantined. Review provenance and the latest error in the data sources panel.',
  'u0459': 'There are {count} authorization-denial audit records. Detailed security information is not exposed to the user; an administrator can review it in audit.',
  'u0460': '{count} automated transitions failed. The incident remains in the audit record and requires human review.',
  'u0461': '{count} privacy/restriction appeals are awaiting an administrator decision.',
  'u0462': '{count} conflicts',
  'u0463': '{title}. {message}',
  'u0464': '{title}. {subtitle}. Status: {status}',
  'u0465': 'Activity history, {count} steps',
  'u0466': '{title}. {description}',
  'u0467': '{message}\\\\nTechnical reference: {reference}',
  'u0468': '{label} · {category} · {location}',
  'u0469': '{label}, category: {category}, location: {location}',
  'u0470': '{count} map records at {location}. Zoom in.',
  'u0471': '{title} · {authority}',
  'u0472': 'Loading',
  'u0473': 'You can view the last received data; staff actions remain read-only until the connection returns.',
  'u0474': 'Your draft is preserved on the device. You can submit it when the connection returns.',
  'u0475': 'Verified active',
  'u0476': 'Awaiting verification',
  'u0477': 'Critical review',
  'u0478': 'Assigned after review',
  'u0479': 'estimate, not a guarantee',
  'u0480': 'target, not a guarantee',
  'u0481': 'not a guarantee',
  'u0482': 'The result photo was published after a privacy review.',
  'u0483': 'Field owner',
  'u0484': 'Field team',
  'u0485': 'SLA target range',
  'u0486': 'Starts on field assignment',
  'u0487': 'New estimate',
  'u0488': 'Unassigned',
  'u0489': 'Take photo',
  'u0490': 'Retake',
  'u0491': 'No photo',
  'u0492': 'Public preview is safe',
  'u0493': 'Public display is disabled; human review is required',
  'u0494': 'AI preliminary analysis suggestion',
  'u0495': 'AI partial/unavailable',
  'u0496': 'No automatic suggestion was available; the report will go to human review.',
  'u0497': 'Suggested category: {category} · Confidence: {confidence}%',
  'u0498': 'Select a valid location within Istanbul.',
  'u0499': 'The description must be at least 10 characters.',
  'u0500': 'The interrupted camera flow was restored safely.',
  'u0501': 'Existing incident corroborated',
  'u0502': 'Could not submit; the draft and photo remain on this device.',
  'u0503': 'Type',
  'u0504': 'Photo',
  'u0505': 'Location',
  'u0506': 'Details',
  'u0507': 'Review',
  'u0508': 'Confirm and submit',
  'u0509': 'Continue to photo',
  'u0510': 'Continue',
  'u0511': '{label} (estimate, not a guarantee)',
  'u0512': 'Merged with a similar incident',
  'u0513': 'Review note',
  'u0514': 'The status event was processed safely.',
  'u0515': 'Additional information was saved and sent to the review queue.',
  'u0516': 'Your feedback was received.',
  'u0517': 'Your appeal was recorded for human review.',
  'u0518': 'Report received',
  'u0519': 'Preliminary analysis',
  'u0520': 'Under review',
  'u0521': 'Waiting for additional information',
  'u0522': 'Routed to the responsible unit',
  'u0523': 'Field work in progress',
  'u0524': 'Resolved',
  'u0525': 'Merged',
  'u0526': 'Out of scope',
  'u0527': 'Rejected',
  'u0528': 'Initial checks completed and routed to the responsible unit',
  'u0529': 'Additional information received',
  'u0530': 'Resolution feedback received',
  'u0531': 'Appeal received',
  'u0532': 'Status updated',
  'u0533': 'Report status changed',
  'u0534': 'Additional information requested',
  'u0535': 'Resolution published',
  'u0536': 'Kent Takip notification',
  'u0537': 'Access my data',
  'u0538': 'Correction request',
  'u0539': 'Data deletion request',
  'u0540': 'Object to automated assessment',
  'u0541': 'Monitor incoming reports, incidents, and data health at a glance.',
  'u0542': 'Human review',
  'u0543': 'Enter the evidence and routing rationale',
  'u0544': 'A decision rationale is required.',
  'u0545': 'Role-based menu isolation',
  'u0546': 'Secure deep-link guard',
  'u0547': 'Responsive workspace',
  'u0548': 'Synthetic demo data',
  'u0549': 'Verified information',
  'u0550': 'Privacy focused',
  'u0551': 'Ready',
  'u0552': 'Refreshed with keyboard',
  'u0553': 'e.g. Mesrutiyet Avenue',
  'u0554': 'Planned',
  'u0555': 'Critical review',
  'u0556': 'Tracking no.',
  'u0557': 'Unit',
  'u0558': 'Status',
  'u0559': 'Routed',
  'u0560': 'Today, 10:42',
  'u0561': 'Today, 11:03',
  'u0562': 'Waiting.',
  'u0563': 'Show password',
  'u0564': 'Hide password',
  'u0565': 'A separate description field is not available in this snapshot.',
  'u0566': 'Staff member left the review workspace.',
  'u0567': 'Why are you taking over this review?',
  'u0568': 'The public preview cannot be published without human approval.',
  'u0569': 'An additional-information message is required.',
  'u0570': 'Close critical record',
  'u0571': 'Are you sure you want to {action} this record with a critical signal?',
  'u0572': 'Source',
  'u0573': 'Target',
  'u0574': 'Critical',
  'u0575': 'High priority',
  'u0576': 'Normal',
  'u0577': 'Low confidence',
  'u0578': 'Privacy',
  'u0579': 'Abuse',
  'u0580': 'Manual / AI error',
  'u0581': 'Priority + oldest',
  'u0582': 'Oldest',
  'u0583': 'Newest',
  'u0584': 'Duplicate probability',
  'u0585': 'reject',
  'u0586': 'mark out of scope',
  'u0587': 'request additional information',
  'u0588': 'merge',
  'u0589': 'route to IBB',
  'u0590': 'route to district',
  'u0591': 'transfer back',
  'u0592': 'locked',
  'u0593': 'Fresh',
  'u0594': 'Stale',
  'u0595': 'Quarantined',
  'u0596': 'Disabled',
  'u0597': 'Unavailable',
  'u0598': 'Authorized municipal entry with field confirmation',
  'u0599': 'The request was accepted through authorized human review.',
  'u0600': 'The request was rejected with rationale through authorized human review.',
  'u0601': 'Guest',
  'u0602': 'Citizen',
  'u0603': 'Reviewer',
  'u0604': 'Unit Officer',
  'u0605': 'Planner',
  'u0606': 'System Admin',
  'u0607': 'Demo Supervisor',
  'u0608': 'Operations update',
  'u0609': 'Field access was delayed',
  'u0610': 'Unassigned',
  'u0611': 'Assigned to me',
  'u0612': 'Assigned to field team',
  'u0613': 'In progress',
  'u0614': 'Overdue',
  'u0615': 'Planned road maintenance work',
  'u0616': 'The draft is autosaved after the required fields are valid.',
  'u0617': 'Draft {id} is being autosaved.',
  'u0618': '1. Work type',
  'u0619': '2. Location · latitude',
  'u0620': 'Location · longitude',
  'u0621': '3. Impact radius (m)',
  'u0622': '4. Start (UTC ISO-8601)',
  'u0623': 'Estimated end (UTC ISO-8601)',
  'u0624': '5. Responsible unit',
  'u0625': '6. Description',
  'u0626': 'Saving…',
  'u0627': 'Save draft',
  'u0628': 'Draft impact center · not public',
  'u0629': 'Staff draft preview',
  'u0630': '{label}, operation in progress',
  'u0631': 'Completed',
  'u0632': 'Pending',
  'u0633': 'Active incident',
  'u0634': 'Appeal',
  'u0635': 'reject',
  'u0636': 'mark out of scope',
  'u0637': 'Status record',
  'u0638': 'Time',
  'u0639': '{days}d {hours}h',
  'u0640': '{hours}h {minutes}m',
  'u0641': '{minutes}m',
  'u0642': '{distance} km',
  'u0643': '{distance} m',
  'u0644': '{tracking}: {decision} was saved.',

  'u0645': 'Not added',
  'u0646': 'Metadata cleaned',
  'u0647': 'Back',
  'u0648': 'Active',
  'u0649': 'All',
  'u0650': 'Beyoglu',
  'u0651': 'Mesrutiyet Avenue, Sishane',

  'u0652': 'Page not found',
  'u0653': 'Ingested',

  'u0654': '+90 (555) 000-1122',

  'u0655': 'Demo code: {code}',
  'u0656': '{message} {seconds} sec.',
  'u0657': 'Synthetic demo',
  'u0658': 'AI: {ai} · Privacy: {privacy} · {connectivity}',
  'u0659': 'operation',
  'u0660': 'role',
  'u0661': 'appeal',
  'u0662': 'Authority',

  'u0663': 'Refresh',
  'u0664': 'Camera permission was denied. You can grant permission in settings or continue without a photo.',
  'u0665': 'Camera access is restricted on this device. You can continue without a photo.',
  'u0666': 'No camera is available on this device.',
  'u0667': 'The camera operation could not be completed.',
  'u0668': 'The photo must not exceed 8 MB.',
  'u0669': 'The camera operation was cancelled.',
  'u0670': 'The photo format could not be processed safely.',
  'u0671': 'The action could not be completed safely. Technical code: {code}',

  'u0672': 'Pilot KPI and ROI',
  'u0673': 'Derived only from demo or pilot events. It is not a production result or savings claim.',
  'u0674': 'North-star rate',
  'u0675': 'Median first human review',
  'u0676': 'First-pass routing',
  'u0677': 'Duplicate reports per unique incident',
  'u0678': 'Staff AI override rate',
  'u0679': 'Resolution within target',
  'u0680': 'Repeat status request rate',
  'u0681': 'Resolution confirmation rate',
  'u0682': 'Not enough data',
  'u0683': 'ROI calculator',
  'u0684': 'No monetary result is calculated until every input is provided.',
  'u0685': 'Baseline triage minutes',
  'u0686': 'Pilot triage minutes',
  'u0687': 'Monthly reports',
  'u0688': 'Staff cost per minute',
  'u0689': 'Baseline wrong routing',
  'u0690': 'Pilot wrong routing',
  'u0691': 'Rework cost',
  'u0692': 'Baseline duplicate records',
  'u0693': 'Pilot duplicate records',
  'u0694': 'Processing cost per record',
  'u0695': 'Baseline status requests',
  'u0696': 'Pilot status requests',
  'u0697': 'Status request call cost',
  'u0698': 'Infrastructure cost',
  'u0699': 'AI cost',
  'u0700': 'Map cost',
  'u0701': 'SMS cost',
  'u0702': 'Support cost',
  'u0703': 'Operations cost',
  'u0704': 'Calculate',
  'u0705': 'Monthly gross operational benefit',
  'u0706': 'Monthly operating cost',
  'u0707': 'Monthly net impact',
  'u0708': '7-minute jury route',
  'u0709': 'Control center',
  'u0710': 'DemoClock +15 min',
  'u0711': 'DemoClock +1 hour',
  'u0712': 'Simulate source outage',
  'u0713': 'Recover source',
  'u0714': 'Simulate AI failure',
  'u0715': 'Return AI to normal',
  'u0716': 'A Demo Supervisor session is required for this control.',
  'u0717': 'Demo control applied.',
  'u0718': 'Request another status update',
  'u0719': 'Your status request was recorded; priority was not changed automatically.',
  'u0720': 'Pilot targets are hypotheses and must not be presented as achieved results.',
  'u0721': 'Reviewed reports',
  'u0722': 'Routed reports',
  'u0723': 'Resolved incidents',
  'u0724': 'Resolution feedback',
  'u0725': 'Status requests',
  'u0726': 'Step {index}: {start}-{end} sec',
  'u0727': 'Expected evidence: {evidence}',
  'u0728': 'DemoClock offset: {minutes} min',
  'u0729': 'AI mode: {mode}',
  'u0730': 'KPI formulas are calculated from snapshot and immutable audit events.',
  'u0731': 'The ROI formula requires real pilot inputs; blank values are never treated as zero.',
  'u0732': 'Clear inputs',
  'u0733': 'ROI inputs are invalid or incomplete.',
  'u0734': 'Pilot decision template',
  'u0735': 'Baseline, target and go or no-go evidence is kept in the release package template.',

  'u0736': 'In shared mode DemoClock does not change server time; this control is enabled only for local demo mode.',
  'u0737': 'Problem and difference from the current system',
  'u0738': '153 and Istanbul Senin are input channels; Kent Takip is the shared incident layer.',
  'u0739': 'Shared city view',
  'u0740': 'Show the verified incident, planned work, source freshness and accessible list view.',
  'u0741': 'Citizen report',
  'u0742': 'Show privacy-safe media, location, similar incident and controlled corroboration flow.',
  'u0743': 'AI boundary',
  'u0744': 'AI only suggests; rejection, enforcement and public publication remain human decisions.',
  'u0745': 'Municipal incident workspace',
  'u0746': 'Show multiple signals, source, privacy result and human verification and routing.',
  'u0747': 'Closed loop',
  'u0748': 'Show tracking number continuity, timeline updates and resolution evidence.',
  'u0749': 'Source outage and trust',
  'u0750': 'Show real-schema evidence, stale or unavailable fallback and audited media access.',
  'u0751': 'Measurement, pilot and ask',
  'u0752': 'Show the north-star metric, six-week pilot, formula-based ROI and one pilot ask.',
  'u0753': 'Reset demo data',
  'u0754': 'Zoom in',
  'u0755': 'Zoom out',
  'u0756': 'Return to map view',
  'u0757': 'Map focused on {place}.',

};
